### ISSUE TITLE
Adventure option menu translation

### ISSUE THREAD

**Issue by Fabrice-TIERCELIN** [vcmi-mods/swedish-translation#1]
Hi,

I'm about to render the Adventure option menu image:
https://raw.githubusercontent.com/vcmi-mods/italian-translation/vcmi-1.3/italian-translation/content/data/AdvOpts.bmp

I just need the confirmation that this translation (by Google translate) is right:

- Världskarta
- Pusselkarta
- Gräv
- Scenarioinformation
- Spela om motståndarens tur

EDIT: fixed

**Comment by CalZing** [comment]
A little late to the party here. I did the original translation which this repo is based of (just discovered it, and I'm really honored it still has a life). The world map would be "Världskarta" instead of what google suggests. Apart from that, the translations are ok =)

**Comment by XCOM-HUB** [comment]
Yes, "Världskarta" as CalZing wrote 👍
