### ISSUE TITLE
Windmill shows message for the Witch's Hut

### ISSUE THREAD

**Issue by XCOM-HUB** [vcmi-mods/swedish-translation#10]
![Vindkvarnen blev häxkoja](https://github.com/user-attachments/assets/242d9ca6-c285-43e9-ae95-71da38786d11)

I can't figure out why the message for the Witch's Hut shows up when I visit a Windmill. Can someone please help me figure this one out? @misiokles , @heroesiiifan , @Fabrice-TIERCELIN

Windmill = Kvarn/Vindkvarn
Witch's Hut = Häxkoja

There must be something wrong with the following lines/rows in game.json: 

1274 "core.advevent.167": "{Kvarn}\n\nKvarnens ägare hälsar dig: \"Ers Nåd, jag är ledsen men det finns inga resurser i dagsläget.  Kom tillbaka nästa vecka.\"",
1275 "core.advevent.168": "{Kvarn}\n\nKvarnens ägare hälsar dig: \"Ers Nåd, jag har arbetat mycket hårt för att kunna förse er med dessa resurser.  Kom tillbaka nästa vecka om ni vill ha mer.\"",
1276 "core.advevent.169": "{Häxkoja}\n\nEn uråldrig häxa som bor i en märklig koja välkomnar dig.  Hon lär dig %s av någon outgrundlig anledning.",

**Comment by XCOM-HUB** [comment]
I think I found it!

 - "object.core.windmill.name": "Vindkvarn",

It is not the same name as core.advevent.167": "{Kvarn} and core.advevent.168": "{Kvarn}.

I will fix this one right now.

**Comment by Fabrice-TIERCELIN** [comment]
OK, @XCOM-HUB, you can close this ticket

**Comment by XCOM-HUB** [comment]
> OK, @XCOM-HUB, you can close this ticket

The problem is still present, but I have a fix coming up with the full translation soon. It will only take a few more days 😉

**Comment by XCOM-HUB** [comment]
Fixed with Pull Request https://github.com/vcmi-mods/swedish-translation/pull/16 and https://github.com/vcmi-mods/swedish-translation/pull/17 🥳
